table FactInternetSales
	lineageTag: 11540431-1748-465f-9dde-89a0d25f924f

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 2b5514fb-1134-474b-9a47-b33ec35e4e4f
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: 8b355bd3-0275-4c41-a6e4-8c65356e54c6
		summarizeBy: count
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: 30d25504-1187-436e-be78-35bb4e259130
		summarizeBy: count
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: bb3aff2b-67a8-48fc-ae53-6c5b66bdfa10
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 96778157-19da-474b-97ff-08a93493d55c
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: 87315419-bb8a-47c0-be99-d70439c0ebd1
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: cd0a0d82-ca83-4cde-b3b7-67748591fd5d
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 90d9abb0-7189-468a-b0ed-e55c3f29134e
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: 47a13cac-5031-4fef-b1f3-f12a8bfe46c1
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 112cd1c4-19a7-40fb-a1ba-50caabf284d7
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column RevisionNumber
		dataType: int64
		formatString: 0
		lineageTag: f169a89a-80c4-4eb7-8dcb-a37c3b6433f3
		summarizeBy: sum
		sourceColumn: RevisionNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: a9290a23-0027-4a9c-a50d-2e00b8a4304e
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 451d2fd6-4cfa-4b39-989a-3df9f4a8b2c6
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column ExtendedAmount
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 3678033b-5717-4e74-8de9-0232d2f43964
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column UnitPriceDiscountPct
		dataType: double
		lineageTag: af64a4bf-0677-43ef-a416-1ad8fee4ec81
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount
		dataType: double
		lineageTag: 5fe2ad53-304b-46a0-b610-1a35f97adaec
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 5c41033d-34f0-40db-bf2a-bebfa6f04124
		summarizeBy: sum
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column TotalProductCost
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: b726b39a-abf2-41ee-8245-ea937f33d8a9
		summarizeBy: sum
		sourceColumn: TotalProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column SalesAmount
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 8f80c6ff-fbb9-4f7f-903f-d6fd635b16f6
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column TaxAmt
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: f5d804c7-70a1-4a17-ab06-e1b6913210ca
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Freight
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: f0865710-f69d-425f-bc26-1327a813ccfe
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column CarrierTrackingNumber
		dataType: string
		lineageTag: 10332804-181f-47f8-8837-33a1d94f0437
		summarizeBy: none
		sourceColumn: CarrierTrackingNumber

		annotation SummarizationSetBy = Automatic

	column CustomerPONumber
		dataType: string
		lineageTag: abcfa021-d287-4f32-bd87-2faf1d4ee4bf
		summarizeBy: none
		sourceColumn: CustomerPONumber

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: e8f355cd-8fdf-48de-af88-8a44e8c26b44
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column DueDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7b0f757b-30bd-41fc-bec3-7addd21ebbac
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7d0c7016-83fc-44a7-89fe-6d8fe4931945
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

	partition FactInternetSalesNew = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("A01P0717"),
				    AdventureWorksDW2022 = Origen{[Name="AdventureWorksDW2022"]}[Data],
				    dbo_FactInternetSales = AdventureWorksDW2022{[Schema="dbo",Item="FactInternetSales"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(dbo_FactInternetSales, each [OrderDate] >= "01/01/2020" and [OrderDate] < "01/01/2035")
				in
				    #"Filas filtradas"

	partition FactInternetSalesHistory = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("A01P0717"),
				    AdventureWorksDW2022 = Origen{[Name="AdventureWorksDW2022"]}[Data],
				    dbo_FactInternetSales = AdventureWorksDW2022{[Schema="dbo",Item="FactInternetSales"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(dbo_FactInternetSales, each [OrderDate] >= "01/01/2002" and [OrderDate] < "01/01/2020")
				in
				    #"Filas filtradas"
	annotation PBI_ResultType = Table

