title: ADN Fabric
description: Elevar el conocimiento para adoptar MS Fabric
url: ""          # o tu dominio, p.ej. https://adnfabric.github.io
baseurl: ""      # si es project site, p.ej. "/ADNFabric"
permalink: pretty
markdown: kramdown
verbose: true

collections:
  sesiones:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""              # todo el sitio
      type: "sesiones"      # colección 'sesiones'
    values:
      layout: sesion
  - scope:
      path: ""              # resto de páginas
    values:
      layout: default
