title: ADN Fabric
description: Resumen de sesiones y comunidad
url: ""
baseurl: ""
permalink: pretty

collections_dir: .
collections:
  sesiones:
    output: true
    permalink: /:collection/:name/
markdown: kramdown
collections:
  sesiones:
    output: true
    permalink: /:collection/:name
    layout_dir: _layouts
defaults:
  - scope:
      path: ""
      type: "sesiones"
    values:
      layout: sesion
      published: true
  - scope:
      path: ""
    values:
      layout: default
verbose: true