title: ADN Fabric
description: Resumen de sesiones y comunidad
url: ""  # set your custom domain later
baseurl: ""  # leave empty or set subpath
permalink: pretty
layouts_dir: _layouts
theme: null  # Disable the theme to use our own layouts
markdown: kramdown
collections:
  sesiones:
    output: true
    permalink: /:collection/:name
    layout_dir: _layouts
defaults:
  - scope:
      path: ""
      type: "sesiones"
    values:
      layout: sesion
      published: true
  - scope:
      path: ""
    values:
      layout: default
verbose: true