title: ADN Fabric
description: Resumen de sesiones y comunidad
url: ""  # set your custom domain later
baseurl: ""  # leave empty or set subpath
permalink: pretty
markdown: kramdown
collections:
  sesiones:
    output: true
    permalink: /sesiones/:name/
defaults:
  - scope:
      path: ""
      type: "sesiones"
    values:
      layout: sesion
      published: true
  - scope:
      path: ""
    values:
      layout: default