title: ADN Fabric
description: Resumen de sesiones y comunidad
url: ""
baseurl: ""
permalink: pretty

collections:
  sesiones:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: sesiones
    values:
      layout: sesion
markdown: kramdown
collections:
  sesiones:
    output: true
    permalink: /:collection/:name
defaults:
  - scope:
      path: ""
      type: "sesiones"
    values:
      layout: sesion
  - scope:
      path: ""
    values:
      layout: default
verbose: true